M48
; DRILL file {KiCad 7.0.11-2.fc38} date mer 24 apr 2024, 16:28:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-24T16:28:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-2.fc38
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
%
G90
G05
T2
X2.7894Y-2.1122
T1
G00X3.0764Y-2.1122
M15
G01X3.0929Y-2.1122
M16
G05
M30
